# Generated by Django 4.2.6 on 2023-10-20 19:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addr', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Info',
            fields=[
                ('company_number', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('start_date', models.DateField()),
                ('prefix', models.CharField(blank=True, max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=250)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(max_length=150, validators=[django.core.validators.EmailValidator()])),
                ('area_of_work', models.CharField(blank=True, max_length=150)),
                ('disabled', models.BooleanField(blank=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addr.addr_info')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.comp_info')),
            ],
        ),
    ]
