# Generated by Django 2.2.12 on 2023-09-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Info',
            fields=[
                ('company_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('prefix', models.CharField(blank=True, max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=250)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('area_of_work', models.CharField(blank=True, max_length=150)),
                ('disabled', models.BooleanField()),
            ],
        ),
    ]
