# Generated by Django 2.2.12 on 2023-09-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='disabled',
            field=models.BooleanField(blank=True),
        ),
    ]
