# Generated by Django 2.2.12 on 2023-09-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addr_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=250)),
                ('number', models.IntegerField(blank=True)),
                ('others', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('county', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
    ]
