# Generated by Django 4.2.6 on 2023-10-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('population', models.CharField(max_length=15)),
                ('area_km2', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Addr_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=250)),
                ('number', models.IntegerField(blank=True)),
                ('others', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('county', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addr.country_list')),
            ],
        ),
    ]
