# Generated by Django 2.2.12 on 2023-09-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_Info',
            fields=[
                ('identify', models.Field(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.EmailField(blank=True, max_length=255)),
                ('contact', models.CharField(max_length=150)),
                ('activity', models.CharField(max_length=250)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addr.Addr_Info')),
            ],
        ),
    ]
