# Generated by Django 4.2.6 on 2023-10-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_info',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
